### ISSUE TITLE
在最后获得句子的表示(图中M矩阵)后直接过softmax分类器了？？

### ISSUE THREAD

**Issue by tectal** [EmbolismSoil/SelfAttentiveSentenceEmbedding-TF#3]
这里请问是具体如何实现的呢

**Comment by EmbolismSoil** [comment]
原论文是要过全连接网络的，但是我的目的是得到句子的表示，末级分类器太强会削弱句子embedding的表达能力，经过测试直接过softmax的结果得到的句子embedding向量在下游任务中表现更好------------------ 原始邮件 ------------------
发件人: "杨国峰"<notifications@github.com>
发送时间: 2019年5月4日(星期六) 下午5:26
收件人: "EmbolismSoil/SelfAttentiveSentenceEmbedding-TF"<SelfAttentiveSentenceEmbedding-TF@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [EmbolismSoil/SelfAttentiveSentenceEmbedding-TF] 在最后获得句子的表示(图中M矩阵)后直接过softmax分类器了？？ (#3)



这里请问是具体如何实现的呢
 
&mdash;

**Comment by tectal** [comment]
如果就是分类任务，末级分类器太强会削弱句子embedding的表达能力吗？直接过softmax的结果得到的句子embedding向量在下游任务中表现更好——这里如果就是分类任务那么还在后面接一层softmax就可以吗？

**Comment by EmbolismSoil** [comment]
如果分类任务是以高AUC为目的，那么在数据量足够的情况下，加全连接网络会更好。我的场景下不是为了分类，而是为了获取句子的embedding向量，所以分类效果是次要的，获取高质量的句向量才是主要的------------------ 原始邮件 ------------------
发件人: "杨国峰"<notifications@github.com>
发送时间: 2019年5月4日(星期六) 晚上6:25
收件人: "EmbolismSoil/SelfAttentiveSentenceEmbedding-TF"<SelfAttentiveSentenceEmbedding-TF@noreply.github.com>;
抄送: "ConleyLee"<743703241@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [EmbolismSoil/SelfAttentiveSentenceEmbedding-TF] 在最后获得句子的表示(图中M矩阵)后直接过softmax分类器了？？ (#3)



如果就是分类任务，末级分类器太强会削弱句子embedding的表达能力吗？直接过softmax的结果得到的句子embedding向量在下游任务中表现更好——这里如果就是分类任务那么还在后面接一层softmax就可以吗？
 
&mdash;

**Comment by tectal** [comment]
好的，谢谢啦~

**Comment by tectal** [comment]
从<word-id>到<word vector>的映射，你能分享一下这部分转换code吗？谢谢

**Comment by EmbolismSoil** [comment]
Done
